### ISSUE TITLE
Required Primary Region option not supported by CLI

### ISSUE THREAD

**Issue by TheGreatAlgo** [upstash/cli#6]
Was trying to deploy a new upstash via the CLI.

https://upstash.com/docs/devops/developer-api/redis/create_database

Create database for regional was deprecated.

Now it requires primary_region as a variable which is not supported by this CLI.

`error: Unknown option "--primary_region". Did you mean option "--region"?`

**Comment by CahidArda** [comment]
Hi @TheGreatAlgo,

With #7, we updated the CLI to work correctly with primary region option.
